### ISSUE TITLE
Make the old version downloadable again

### ISSUE THREAD

**Issue by seacat17** [xdsopl/robot36#20]
"With version 2, running the decoder in the background will not be supported anymore."

"There will be glitches, there will be bugs"

"No autosave of received image."

Stop enshittification please, or bring the old version back. It worked on Android 4.1.2 and Android 7 just fine and it did it's job.

I don't want to be a beta tester, I want to download the app, like back in 2019, and just decode signals with no trouble, glitches or bugs. I don't care if it's outdated, don't fix what isn't broken.

**Comment by xdsopl** [comment]
> "With version 2, running the decoder in the background will not be supported anymore."

Google made it perfectly clear that recording audio in the background is a big no-no. Re-implementing that feature will be a major undertaking, as Google made it very hard to support such a feature. Sorry, wontfix.

> "There will be glitches, there will be bugs"

And?

> "No autosave of received image."

Of course there is autosave if the calibration header is detected and the mode is supported. Is it not working?

> Stop enshittification please, or bring the old version back. It worked on Android 4.1.2 and Android 7 just fine and it did it's job.

Define enshittification. What exactly is shit? Please create a separate issue for each shit you encounter. And better yet, don't use shitty language if you want to increase your chances of getting your shit fixed. If you rather want the old shit, here you go: https://github.com/xdsopl/robot36/releases/tag/v1.48

> I don't want to be a beta tester, I want to download the app, like back in 2019, and just decode signals with no trouble, glitches or bugs. I don't care if it's outdated, don't fix what isn't broken.

I do this open source project for free. I need beta testers like you who give valuable feedback as I neither have access to each variation of Android device nor the time to test everything on everything. The main reason for the rewrite was for others to better understand the code and eventually contribute, as that haven't happened in over a decade since the release. Another reason was to increase its chances of survival on the Play store, as Google made various changes to the ecosystem over the past decade. You have no idea how much I had to resist the idea of simply abandoning this project.
